# Generated by Django 3.2.8 on 2021-10-29 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0)),
                ('minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0),
                                                                       django.core.validators.MaxValueValidator(60)])),
                ('seconds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0),
                                                                       django.core.validators.MaxValueValidator(60)])),
            ],
        ),
    ]
