# Generated by Django 3.2.8 on 2021-11-29 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ConsoleTrackerApp', '0004_alter_machine_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_uses_machine',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
