# Generated by Django 3.2.8 on 2022-01-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsoleTrackerApp', '0005_auto_20211210_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
