# Generated by Django 3.2.8 on 2021-11-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsoleTrackerApp', '0005_auto_20211128_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
