# Generated by Django 3.2.8 on 2022-02-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ConsoleTrackerApp', '0006_auto_20220121_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
