# Generated by Django 4.0.2 on 2022-02-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsoleTrackerApp', '0008_alter_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_uses_machine',
            name='init_Balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
