# Generated by Django 3.2.8 on 2022-03-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConsoleTrackerApp', '0009_machine_mac'),
        ('ConsoleTrackerApp', '0009_user_uses_machine_init_balance'),
    ]

    operations = [
    ]
